spring:
  autoconfigure:
    exclude:
      - org.redisson.spring.starter.RedissonAutoConfiguration
      - org.redisson.spring.starter.RedissonReactiveAutoConfiguration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gateway01.ap-northeast-1.prod.aws.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2&serverTimezone=Asia/Seoul
    username: 4KPw8TdWa9Uknwp.root
    password: h9cKiMZ8PLerDuWD

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: Asia/Seoul
    show-sql: true
    open-in-view: false
  jackson:
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      token: ${SPRING_DATA_REDIS_TOKEN:}
      ssl: ${SPRING_DATA_REDIS_SSL:false}
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
